//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lie_Detection.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lie_Detection.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.67,FALSE
        ///1.5,FALSE
        ///1.67,FALSE
        ///0.67,FALSE
        ///3,TRUE
        ///1.33,FALSE
        ///1.5,FALSE
        ///0,FALSE
        ///0,FALSE
        ///0.75,FALSE
        ///0,FALSE
        ///2,FALSE
        ///0,FALSE
        ///0,FALSE
        ///1.5,FALSE
        ///0,FALSE
        ///0.5,FALSE
        ///0,FALSE
        ///1.33,FALSE
        ///0,FALSE
        ///0,FALSE
        ///3,TRUE
        ///2,TRUE
        ///3,TRUE
        ///2.5,TRUE
        ///2.5,TRUE
        ///3,TRUE
        ///0,TRUE
        ///4,TRUE
        ///2,TRUE
        ///2,TRUE
        ///4,TRUE
        ///2,TRUE
        ///0,TRUE
        ///2,TRUE
        ///0,TRUE
        ///3,TRUE
        ///2,TRUE
        ///3,TRUE
        ///2.5,TRUE
        ///6.86,TRUE
        ///15,TRUE
        ///3.75,TRUE
        ///2.8,TRUE
        ///2.67,TRUE
        ///1.8,FALSE
        ///1.43,FALSE
        ///0.83,FALSE
        ///1.6,FALSE
        ///4,TRUE
        ///.
        /// </summary>
        public static string EB_TrainingSet {
            get {
                return ResourceManager.GetString("EB_TrainingSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Iron {
            get {
                object obj = ResourceManager.GetObject("Iron", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
